version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - neo4j
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidgraph
    ports:
      - "5432:5432"
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
